In [181]:
import os
import pandas as pd

In [182]:
fifteen_path = os.path.join('raw/2015.csv')
sixteen_path = os.path.join('raw/2016.csv')
seventeen_path = os.path.join('raw/2017.csv')
eighteen_path = os.path.join('raw/2018.csv')
nineteen_path = os.path.join('raw/2019.csv')
twenty_path = os.path.join('raw/2020.csv')
#country_path = os.path.join('clean/countries.csv')

In [183]:
happiness_15_df = pd.read_csv(fifteen_path)
happiness_16_df = pd.read_csv(sixteen_path)
happiness_17_df = pd.read_csv(seventeen_path)
happiness_18_df = pd.read_csv(eighteen_path)
happiness_19_df = pd.read_csv(nineteen_path)
happiness_20_df = pd.read_csv(twenty_path)
#country_df = pd.read_csv(country_path)

In [184]:
happiness_15_df.rename(columns = {'Economy (GDP per Capita)':'Wealth', 'Health (Life Expectancy)': "Health", 'Trust (Government Corruption)': 'Trust'}, inplace = True)
happiness_15_df['Year'] = pd.Series([2015 for x in range(len(happiness_15_df.index))]) 
happiness_15_df.drop(columns=['Standard Error', 'Dystopia Residual'])
happiness_15_df.loc[happiness_15_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_15_df.loc[happiness_15_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_15_df.loc[happiness_15_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_15_df.loc[happiness_15_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_15_df.loc[happiness_15_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2015 = happiness_15_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2015.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
152,Afghanistan,153,3.575,0.31982,0.30285,0.30335,0.23414,0.09719,0.36510,2015
94,Albania,95,4.959,0.87867,0.80434,0.81325,0.35733,0.06413,0.14272,2015
67,Algeria,68,5.605,0.93929,1.07772,0.61766,0.28579,0.17383,0.07822,2015
136,Angola,137,4.033,0.75778,0.86040,0.16683,0.10384,0.07122,0.12344,2015
29,Argentina,30,6.574,1.05351,1.24823,0.78723,0.44974,0.08484,0.11451,2015

In [185]:
happiness_16_df.rename(columns = {'Economy (GDP per Capita)':'Wealth', 'Health (Life Expectancy)': "Health", 'Trust (Government Corruption)': 'Trust'}, inplace = True)
happiness_16_df.drop(columns=['Lower Confidence Interval', 'Upper Confidence Interval','Dystopia Residual'])
happiness_16_df['Year'] = pd.Series([2016 for x in range(len(happiness_16_df.index))])
happiness_16_df.loc[happiness_16_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_16_df.loc[happiness_16_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_16_df.loc[happiness_16_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_16_df.loc[happiness_16_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_16_df.loc[happiness_16_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2016 = happiness_16_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2016.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
153,Afghanistan,154,3.360,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2016
108,Albania,109,4.655,0.95530,0.50163,0.73007,0.31866,0.05301,0.16840,2016
37,Algeria,38,6.355,1.05266,0.83309,0.61804,0.21006,0.16157,0.07044,2016
140,Angola,141,3.866,0.84731,0.66366,0.04991,0.00589,0.08434,0.12071,2016
25,Argentina,26,6.650,1.15137,1.06612,0.69711,0.42284,0.07296,0.10989,2016

In [186]:
happiness_17_df.rename(columns = {'Happiness.Rank':'Happiness Rank', 'Happiness.Score':'Happiness Score','Economy..GDP.per.Capita.':'Wealth', 'Health..Life.Expectancy.': "Health", 'Trust..Government.Corruption.': 'Trust'}, inplace = True)
happiness_17_df['Year'] = pd.Series([2017 for x in range(len(happiness_17_df.index))]) 
happiness_17_df.loc[happiness_17_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_17_df.loc[happiness_17_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_17_df.loc[happiness_17_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_17_df.loc[happiness_17_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_17_df.loc[happiness_17_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2017 = happiness_17_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2017.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
140,Afghanistan,141,3.794,0.401477,0.581543,0.180747,0.106180,0.061158,0.311871,2017
108,Albania,109,4.644,0.996193,0.803685,0.731160,0.381499,0.039864,0.201313,2017
52,Algeria,53,5.872,1.091864,1.146217,0.617585,0.233336,0.146096,0.069437,2017
139,Angola,140,3.795,0.858428,1.104412,0.049869,0.000000,0.069720,0.097926,2017
23,Argentina,24,6.599,1.185295,1.440451,0.695137,0.494519,0.059740,0.109457,2017

In [187]:
happiness_18_df.rename(columns = {'Country or region':'Country','Overall rank':'Happiness Rank', 'Score':'Happiness Score','Social support':'Family','GDP per capita':'Wealth', 'Healthy life expectancy': "Health", 'Perceptions of corruption': 'Trust', 'Freedom to make life choices':'Freedom'}, inplace = True)
happiness_18_df['Year'] = pd.Series([2018 for x in range(len(happiness_18_df.index))]) 
happiness_18_df.loc[happiness_18_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_18_df.loc[happiness_18_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_18_df.loc[happiness_18_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_18_df.loc[happiness_18_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_18_df.loc[happiness_18_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2018 = happiness_18_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2018.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
144,Afghanistan,145,3.632,0.332,0.537,0.255,0.085,0.036,0.191,2018
111,Albania,112,4.586,0.916,0.817,0.790,0.419,0.032,0.149,2018
83,Algeria,84,5.295,0.979,1.154,0.687,0.077,0.135,0.055,2018
141,Angola,142,3.795,0.730,1.125,0.269,0.000,0.061,0.079,2018
28,Argentina,29,6.388,1.073,1.468,0.744,0.570,0.054,0.062,2018

In [188]:
happiness_19_df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [189]:
happiness_19_df.rename(columns = {'Country or region':'Country','Overall rank':'Happiness Rank', 'Score':'Happiness Score','Social support':'Family','GDP per capita':'Wealth', 'Healthy life expectancy': "Health", 'Perceptions of corruption': 'Trust', 'Freedom to make life choices':'Freedom'}, inplace = True)
happiness_19_df['Year'] = pd.Series([2019 for x in range(len(happiness_19_df.index))]) 
happiness_19_df.loc[happiness_19_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_19_df.loc[happiness_19_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_19_df.loc[happiness_19_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_19_df.loc[happiness_19_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_19_df.loc[happiness_19_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2019 = happiness_19_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2019.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
153,Afghanistan,154,3.203,0.350,0.517,0.361,0.000,0.025,0.158,2019
106,Albania,107,4.719,0.947,0.848,0.874,0.383,0.027,0.178,2019
87,Algeria,88,5.211,1.002,1.160,0.785,0.086,0.114,0.073,2019
46,Argentina,47,6.086,1.092,1.432,0.881,0.471,0.050,0.066,2019
115,Armenia,116,4.559,0.850,1.055,0.815,0.283,0.064,0.095,2019

In [193]:
happiness_20_df["Happiness Rank"] = 1 + happiness_20_df.index
happiness_20_df.head()

,Country,Region,Happiness Score,Standard error of ladder score,upperwhisker,lowerwhisker,Wealth,Family,Health,Freedom,...,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Happiness Rank,Year
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,...,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835,1,2020
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,...,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741,2,2020
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,...,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267,3,2020
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,...,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688,4,2020
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,...,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266,5,2020

In [194]:
happiness_20_df.rename(columns = {'Country name':'Country', 'Regional indicator':'Region','Ladder score':'Happiness Score','Social support':'Family','Logged GDP per capita':'Wealth', 'Healthy life expectancy': "Health", 'Perceptions of corruption': 'Trust', 'Freedom to make life choices':'Freedom'}, inplace = True)
happiness_20_df['Year'] = pd.Series([2020 for x in range(len(happiness_20_df.index))]) 
happiness_20_df.loc[happiness_20_df['Country'] == 'Hong Kong S.A.R., China', 'Country'] = 'Hong Kong'
happiness_20_df.loc[happiness_20_df['Country'] == 'Hong Kong S.A.R. of China', 'Country'] = 'Hong Kong'
happiness_20_df.loc[happiness_20_df['Country'] == 'Somaliland region', 'Country'] = 'Somaliland Region'
happiness_20_df.loc[happiness_20_df['Country'] == 'Taiwan Province of China', 'Country'] = 'Taiwan'
happiness_20_df.loc[happiness_20_df['Country'] == 'Trinidad and Tobago', 'Country'] = 'Trinidad & Tobago'
Clean2020 = happiness_20_df[['Country', 'Happiness Rank', 'Happiness Score', 'Wealth', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity', 'Year']].copy()
Clean2020.sort_values(by=['Country']).head()

,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
152,Afghanistan,153,2.5669,7.462861,0.470367,52.590000,0.396573,0.933687,-0.096429,2020
104,Albania,105,4.8827,9.417931,0.671070,68.708138,0.781994,0.896304,-0.042309,2020
99,Algeria,100,5.0051,9.537965,0.803385,65.905174,0.466611,0.735485,-0.121105,2020
54,Argentina,55,5.9747,9.810955,0.900568,68.803802,0.831132,0.842010,-0.194914,2020
115,Armenia,116,4.6768,9.100476,0.757479,66.750656,0.712018,0.773545,-0.138780,2020

In [197]:
list_2015 = []
for country in Clean2015['Country']:
    list_2015.append(country)
list_2016 = []
for country in Clean2016['Country']:
    list_2016.append(country)
list_2017 = []
for country in Clean2017['Country']:
    list_2017.append(country)
list_2018 = []
for country in Clean2018['Country']:
    list_2018.append(country)
list_2019 = []
for country in Clean2019['Country']:
    list_2019.append(country)
list_2020 = []
for country in Clean2020['Country']:
    list_2020.append(country)

In [198]:
print(list_2015)
print(list_2016)
print(list_2017)
print(list_2018)
print(list_2019)
print(list_2020)

['Switzerland', 'Iceland', 'Denmark', 'Norway', 'Canada', 'Finland', 'Netherlands', 'Sweden', 'New Zealand', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'Mexico', 'United States', 'Brazil', 'Luxembourg', 'Ireland', 'Belgium', 'United Arab Emirates', 'United Kingdom', 'Oman', 'Venezuela', 'Singapore', 'Panama', 'Germany', 'Chile', 'Qatar', 'France', 'Argentina', 'Czech Republic', 'Uruguay', 'Colombia', 'Thailand', 'Saudi Arabia', 'Spain', 'Malta', 'Taiwan', 'Kuwait', 'Suriname', 'Trinidad & Tobago', 'El Salvador', 'Guatemala', 'Uzbekistan', 'Slovakia', 'Japan', 'South Korea', 'Ecuador', 'Bahrain', 'Italy', 'Bolivia', 'Moldova', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Nicaragua', 'Peru', 'Belarus', 'Poland', 'Malaysia', 'Croatia', 'Libya', 'Russia', 'Jamaica', 'North Cyprus', 'Cyprus', 'Algeria', 'Kosovo', 'Turkmenistan', 'Mauritius', 'Hong Kong', 'Estonia', 'Indonesia', 'Vietnam', 'Turkey', 'Kyrgyzstan', 'Nigeria', 'Bhutan', 'Azerbaijan', 'Pakistan', 'Jordan', 'Montenegro', 'China', 'Zambia', 'Romania', 'Serbia', 'Portugal', 'Latvia', 'Philippines', 'Somaliland Region', 'Morocco', 'Macedonia', 'Mozambique', 'Albania', 'Bosnia and Herzegovina', 'Lesotho', 'Dominican Republic', 'Laos', 'Mongolia', 'Swaziland', 'Greece', 'Lebanon', 'Hungary', 'Honduras', 'Tajikistan', 'Tunisia', 'Palestinian Territories', 'Bangladesh', 'Iran', 'Ukraine', 'Iraq', 'South Africa', 'Ghana', 'Zimbabwe', 'Liberia', 'India', 'Sudan', 'Haiti', 'Congo (Kinshasa)', 'Nepal', 'Ethiopia', 'Sierra Leone', 'Mauritania', 'Kenya', 'Djibouti', 'Armenia', 'Botswana', 'Myanmar', 'Georgia', 'Malawi', 'Sri Lanka', 'Cameroon', 'Bulgaria', 'Egypt', 'Yemen', 'Angola', 'Mali', 'Congo (Brazzaville)', 'Comoros', 'Uganda', 'Senegal', 'Gabon', 'Niger', 'Cambodia', 'Tanzania', 'Madagascar', 'Central African Republic', 'Chad', 'Guinea', 'Ivory Coast', 'Burkina Faso', 'Afghanistan', 'Rwanda', 'Benin', 'Syria', 'Burundi', 'Togo']
['Denmark', 'Switzerland', 'Iceland', 'Norway', 'Finland', 'Canada', 'Netherlands', 'New Zealand', 'Australia', 'Sweden', 'Israel', 'Austria', 'United States', 'Costa Rica', 'Puerto Rico', 'Germany', 'Brazil', 'Belgium', 'Ireland', 'Luxembourg', 'Mexico', 'Singapore', 'United Kingdom', 'Chile', 'Panama', 'Argentina', 'Czech Republic', 'United Arab Emirates', 'Uruguay', 'Malta', 'Colombia', 'France', 'Thailand', 'Saudi Arabia', 'Taiwan', 'Qatar', 'Spain', 'Algeria', 'Guatemala', 'Suriname', 'Kuwait', 'Bahrain', 'Trinidad & Tobago', 'Venezuela', 'Slovakia', 'El Salvador', 'Malaysia', 'Nicaragua', 'Uzbekistan', 'Italy', 'Ecuador', 'Belize', 'Japan', 'Kazakhstan', 'Moldova', 'Russia', 'Poland', 'South Korea', 'Bolivia', 'Lithuania', 'Belarus', 'North Cyprus', 'Slovenia', 'Peru', 'Turkmenistan', 'Mauritius', 'Libya', 'Latvia', 'Cyprus', 'Paraguay', 'Romania', 'Estonia', 'Jamaica', 'Croatia', 'Hong Kong', 'Somalia', 'Kosovo', 'Turkey', 'Indonesia', 'Jordan', 'Azerbaijan', 'Philippines', 'China', 'Bhutan', 'Kyrgyzstan', 'Serbia', 'Bosnia and Herzegovina', 'Montenegro', 'Dominican Republic', 'Morocco', 'Hungary', 'Pakistan', 'Lebanon', 'Portugal', 'Macedonia', 'Vietnam', 'Somaliland Region', 'Tunisia', 'Greece', 'Tajikistan', 'Mongolia', 'Laos', 'Nigeria', 'Honduras', 'Iran', 'Zambia', 'Nepal', 'Palestinian Territories', 'Albania', 'Bangladesh', 'Sierra Leone', 'Iraq', 'Namibia', 'Cameroon', 'Ethiopia', 'South Africa', 'Sri Lanka', 'India', 'Myanmar', 'Egypt', 'Armenia', 'Kenya', 'Ukraine', 'Ghana', 'Congo (Kinshasa)', 'Georgia', 'Congo (Brazzaville)', 'Senegal', 'Bulgaria', 'Mauritania', 'Zimbabwe', 'Malawi', 'Sudan', 'Gabon', 'Mali', 'Haiti', 'Botswana', 'Comoros', 'Ivory Coast', 'Cambodia', 'Angola', 'Niger', 'South Sudan', 'Chad', 'Burkina Faso', 'Uganda', 'Yemen', 'Madagascar', 'Tanzania', 'Liberia', 'Guinea', 'Rwanda', 'Benin', 'Afghanistan', 'Togo', 'Syria', 'Burundi']
['Norway', 'Denmark', 'Iceland', 'Switzerland', 'Finland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'United States', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United Kingdom', 'Chile', 'United Arab Emirates', 'Brazil', 'Czech Republic', 'Argentina', 'Mexico', 'Singapore', 'Malta', 'Uruguay', 'Guatemala', 'Panama', 'France', 'Thailand', 'Taiwan', 'Spain', 'Qatar', 'Colombia', 'Saudi Arabia', 'Trinidad & Tobago', 'Kuwait', 'Slovakia', 'Bahrain', 'Malaysia', 'Nicaragua', 'Ecuador', 'El Salvador', 'Poland', 'Uzbekistan', 'Italy', 'Russia', 'Belize', 'Japan', 'Lithuania', 'Algeria', 'Latvia', 'South Korea', 'Moldova', 'Romania', 'Bolivia', 'Turkmenistan', 'Kazakhstan', 'North Cyprus', 'Slovenia', 'Peru', 'Mauritius', 'Cyprus', 'Estonia', 'Belarus', 'Libya', 'Turkey', 'Paraguay', 'Hong Kong', 'Philippines', 'Serbia', 'Jordan', 'Hungary', 'Jamaica', 'Croatia', 'Kosovo', 'China', 'Pakistan', 'Indonesia', 'Venezuela', 'Montenegro', 'Morocco', 'Azerbaijan', 'Dominican Republic', 'Greece', 'Lebanon', 'Portugal', 'Bosnia and Herzegovina', 'Honduras', 'Macedonia', 'Somalia', 'Vietnam', 'Nigeria', 'Tajikistan', 'Bhutan', 'Kyrgyzstan', 'Nepal', 'Mongolia', 'South Africa', 'Tunisia', 'Palestinian Territories', 'Egypt', 'Bulgaria', 'Sierra Leone', 'Cameroon', 'Iran', 'Albania', 'Bangladesh', 'Namibia', 'Kenya', 'Mozambique', 'Myanmar', 'Senegal', 'Zambia', 'Iraq', 'Gabon', 'Ethiopia', 'Sri Lanka', 'Armenia', 'India', 'Mauritania', 'Congo (Brazzaville)', 'Georgia', 'Congo (Kinshasa)', 'Mali', 'Ivory Coast', 'Cambodia', 'Sudan', 'Ghana', 'Ukraine', 'Uganda', 'Burkina Faso', 'Niger', 'Malawi', 'Chad', 'Zimbabwe', 'Lesotho', 'Angola', 'Afghanistan', 'Botswana', 'Benin', 'Madagascar', 'Haiti', 'Yemen', 'South Sudan', 'Liberia', 'Guinea', 'Togo', 'Rwanda', 'Syria', 'Tanzania', 'Burundi', 'Central African Republic']
['Finland', 'Norway', 'Denmark', 'Iceland', 'Switzerland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'United Kingdom', 'Austria', 'Costa Rica', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United States', 'Israel', 'United Arab Emirates', 'Czech Republic', 'Malta', 'France', 'Mexico', 'Chile', 'Taiwan', 'Panama', 'Brazil', 'Argentina', 'Guatemala', 'Uruguay', 'Qatar', 'Saudi Arabia', 'Singapore', 'Malaysia', 'Spain', 'Colombia', 'Trinidad & Tobago', 'Slovakia', 'El Salvador', 'Nicaragua', 'Poland', 'Bahrain', 'Uzbekistan', 'Kuwait', 'Thailand', 'Italy', 'Ecuador', 'Belize', 'Lithuania', 'Slovenia', 'Romania', 'Latvia', 'Japan', 'Mauritius', 'Jamaica', 'South Korea', 'Northern Cyprus', 'Russia', 'Kazakhstan', 'Cyprus', 'Bolivia', 'Estonia', 'Paraguay', 'Peru', 'Kosovo', 'Moldova', 'Turkmenistan', 'Hungary', 'Libya', 'Philippines', 'Honduras', 'Belarus', 'Turkey', 'Pakistan', 'Hong Kong', 'Portugal', 'Serbia', 'Greece', 'Lebanon', 'Montenegro', 'Croatia', 'Dominican Republic', 'Algeria', 'Morocco', 'China', 'Azerbaijan', 'Tajikistan', 'Macedonia', 'Jordan', 'Nigeria', 'Kyrgyzstan', 'Bosnia and Herzegovina', 'Mongolia', 'Vietnam', 'Indonesia', 'Bhutan', 'Somalia', 'Cameroon', 'Bulgaria', 'Nepal', 'Venezuela', 'Gabon', 'Palestinian Territories', 'South Africa', 'Iran', 'Ivory Coast', 'Ghana', 'Senegal', 'Laos', 'Tunisia', 'Albania', 'Sierra Leone', 'Congo (Brazzaville)', 'Bangladesh', 'Sri Lanka', 'Iraq', 'Mali', 'Namibia', 'Cambodia', 'Burkina Faso', 'Egypt', 'Mozambique', 'Kenya', 'Zambia', 'Mauritania', 'Ethiopia', 'Georgia', 'Armenia', 'Myanmar', 'Chad', 'Congo (Kinshasa)', 'India', 'Niger', 'Uganda', 'Benin', 'Sudan', 'Ukraine', 'Togo', 'Guinea', 'Lesotho', 'Angola', 'Madagascar', 'Zimbabwe', 'Afghanistan', 'Botswana', 'Malawi', 'Haiti', 'Liberia', 'Syria', 'Rwanda', 'Yemen', 'Tanzania', 'South Sudan', 'Central African Republic', 'Burundi']
['Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands', 'Switzerland', 'Sweden', 'New Zealand', 'Canada', 'Austria', 'Australia', 'Costa Rica', 'Israel', 'Luxembourg', 'United Kingdom', 'Ireland', 'Germany', 'Belgium', 'United States', 'Czech Republic', 'United Arab Emirates', 'Malta', 'Mexico', 'France', 'Taiwan', 'Chile', 'Guatemala', 'Saudi Arabia', 'Qatar', 'Spain', 'Panama', 'Brazil', 'Uruguay', 'Singapore', 'El Salvador', 'Italy', 'Bahrain', 'Slovakia', 'Trinidad & Tobago', 'Poland', 'Uzbekistan', 'Lithuania', 'Colombia', 'Slovenia', 'Nicaragua', 'Kosovo', 'Argentina', 'Romania', 'Cyprus', 'Ecuador', 'Kuwait', 'Thailand', 'Latvia', 'South Korea', 'Estonia', 'Jamaica', 'Mauritius', 'Japan', 'Honduras', 'Kazakhstan', 'Bolivia', 'Hungary', 'Paraguay', 'Northern Cyprus', 'Peru', 'Portugal', 'Pakistan', 'Russia', 'Philippines', 'Serbia', 'Moldova', 'Libya', 'Montenegro', 'Tajikistan', 'Croatia', 'Hong Kong', 'Dominican Republic', 'Bosnia and Herzegovina', 'Turkey', 'Malaysia', 'Belarus', 'Greece', 'Mongolia', 'North Macedonia', 'Nigeria', 'Kyrgyzstan', 'Turkmenistan', 'Algeria', 'Morocco', 'Azerbaijan', 'Lebanon', 'Indonesia', 'China', 'Vietnam', 'Bhutan', 'Cameroon', 'Bulgaria', 'Ghana', 'Ivory Coast', 'Nepal', 'Jordan', 'Benin', 'Congo (Brazzaville)', 'Gabon', 'Laos', 'South Africa', 'Albania', 'Venezuela', 'Cambodia', 'Palestinian Territories', 'Senegal', 'Somalia', 'Namibia', 'Niger', 'Burkina Faso', 'Armenia', 'Iran', 'Guinea', 'Georgia', 'Gambia', 'Kenya', 'Mauritania', 'Mozambique', 'Tunisia', 'Bangladesh', 'Iraq', 'Congo (Kinshasa)', 'Mali', 'Sierra Leone', 'Sri Lanka', 'Myanmar', 'Chad', 'Ukraine', 'Ethiopia', 'Swaziland', 'Uganda', 'Egypt', 'Zambia', 'Togo', 'India', 'Liberia', 'Comoros', 'Madagascar', 'Lesotho', 'Burundi', 'Zimbabwe', 'Haiti', 'Botswana', 'Syria', 'Malawi', 'Yemen', 'Rwanda', 'Tanzania', 'Afghanistan', 'Central African Republic', 'South Sudan']
['Finland', 'Denmark', 'Switzerland', 'Iceland', 'Norway', 'Netherlands', 'Sweden', 'New Zealand', 'Austria', 'Luxembourg', 'Canada', 'Australia', 'United Kingdom', 'Israel', 'Costa Rica', 'Ireland', 'Germany', 'United States', 'Czech Republic', 'Belgium', 'United Arab Emirates', 'Malta', 'France', 'Mexico', 'Taiwan', 'Uruguay', 'Saudi Arabia', 'Spain', 'Guatemala', 'Italy', 'Singapore', 'Brazil', 'Slovenia', 'El Salvador', 'Kosovo', 'Panama', 'Slovakia', 'Uzbekistan', 'Chile', 'Bahrain', 'Lithuania', 'Trinidad & Tobago', 'Poland', 'Colombia', 'Cyprus', 'Nicaragua', 'Romania', 'Kuwait', 'Mauritius', 'Kazakhstan', 'Estonia', 'Philippines', 'Hungary', 'Thailand', 'Argentina', 'Honduras', 'Latvia', 'Ecuador', 'Portugal', 'Jamaica', 'South Korea', 'Japan', 'Peru', 'Serbia', 'Bolivia', 'Pakistan', 'Paraguay', 'Dominican Republic', 'Bosnia and Herzegovina', 'Moldova', 'Tajikistan', 'Montenegro', 'Russia', 'Kyrgyzstan', 'Belarus', 'North Cyprus', 'Greece', 'Hong Kong', 'Croatia', 'Libya', 'Mongolia', 'Malaysia', 'Vietnam', 'Indonesia', 'Ivory Coast', 'Benin', 'Maldives', 'Congo (Brazzaville)', 'Azerbaijan', 'Macedonia', 'Ghana', 'Nepal', 'Turkey', 'China', 'Turkmenistan', 'Bulgaria', 'Morocco', 'Cameroon', 'Venezuela', 'Algeria', 'Senegal', 'Guinea', 'Niger', 'Laos', 'Albania', 'Cambodia', 'Bangladesh', 'Gabon', 'South Africa', 'Iraq', 'Lebanon', 'Burkina Faso', 'Gambia', 'Mali', 'Nigeria', 'Armenia', 'Georgia', 'Iran', 'Jordan', 'Mozambique', 'Kenya', 'Namibia', 'Ukraine', 'Liberia', 'Palestinian Territories', 'Uganda', 'Chad', 'Tunisia', 'Mauritania', 'Sri Lanka', 'Congo (Kinshasa)', 'Swaziland', 'Myanmar', 'Comoros', 'Togo', 'Ethiopia', 'Madagascar', 'Egypt', 'Sierra Leone', 'Burundi', 'Zambia', 'Haiti', 'Lesotho', 'India', 'Malawi', 'Yemen', 'Botswana', 'Tanzania', 'Central African Republic', 'Rwanda', 'Zimbabwe', 'South Sudan', 'Afghanistan']

In [199]:
country_list = []
def list_country(l):
    for country in l:
        if country in country_list:
            continue
        else:
            country_list.append(country)

In [200]:
list_country(list_2015)
list_country(list_2016)
list_country(list_2017)
list_country(list_2018)
list_country(list_2019)
list_country(list_2020)

In [201]:
country_list.sort()

In [202]:
country_list

['Afghanistan',
 'Albania',
 'Algeria',
 'Angola',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahrain',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Costa Rica',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Estonia',
 'Ethiopia',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Guinea',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Cyprus',
 'North Macedonia',
 'Northern Cyprus',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestinian Territories',
 'Panama',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Somalia',
 'Somaliland Region',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Trinidad & Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [203]:
country_id = []
counter = 1
for country in country_list:
    country_id.append(counter)
    counter += 1

In [204]:
country_data = {'country':country_list}

In [205]:
country_data

{'country': ['Afghanistan',
  'Albania',
  'Algeria',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guinea',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Cyprus',
  'North Macedonia',
  'Northern Cyprus',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian Territories',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'Somaliland Region',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe']}

In [206]:
country_df = pd.DataFrame.from_dict(country_data)

In [207]:
country_df.to_csv(os.path.join('clean/countries.csv'))

In [210]:
Clean2015.to_csv(os.path.join('clean/2015.csv'))
Clean2016.to_csv(os.path.join('clean/2016.csv'))
Clean2017.to_csv(os.path.join('clean/2017.csv'))
Clean2018.to_csv(os.path.join('clean/2018.csv'))
Clean2019.to_csv(os.path.join('clean/2019.csv'))
Clean2020.to_csv(os.path.join('clean/2020.csv'))

In [212]:
yoy_trend = pd.concat(map(pd.read_csv, ['clean/2015.csv', 'clean/2016.csv','clean/2017.csv', 'clean/2018.csv', 'clean/2018.csv','clean/2020.csv']))
yoy_trend.head()

,Unnamed: 0,Country,Happiness Rank,Happiness Score,Wealth,Family,Health,Freedom,Trust,Generosity,Year
0,0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [213]:
yoy_trend.to_csv(os.path.join('clean/yoy_trend.csv'))